kind: Service
apiVersion: v1
metadata:
  name: helidon-quickstart-hrapp
  labels:
    app: helidon-quickstart-hrapp
spec:
  type: NodePort
  selector:
    app: helidon-quickstart-hrapp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-quickstart-hrapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-quickstart-hrapp
  template:
    metadata:
      labels:
        app: helidon-quickstart-hrapp
        version: v1
    spec:
      containers:
      - name: helidon-quickstart-hrapp
        image: helidon-quickstart-hrapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
